PRODUCT_PACKAGES += \
                    audio.primary.tegra_32 \
                    libnvos_32 \
                    libnvoice_32 \
                    libnvaudiofx_32 \
                    gralloc.tegra_32 \
                    libnvgr_32 \
                    libnvrm_32 \
                    libnvrm_graphics_32 \
                    libnvblit_32 \
                    libnvddk_vic_32 \
                    libnvrm_gpu_32 \
                    hdmi_cec.tegra_32 \
                    hwcomposer.tegra_32 \
                    libnvhwc_service_32 \
                    libtlk_secure_hdcp_up_32 \
                    libtsechdcp_32 \
                    keystore.tegra_32 \
                    memtrack.tegra_32 \
                    vulkan.tegra_32 \
                    hdmi_cec.tegra \
                    gralloc.tegra \
                    libnvgr \
                    libnvos \
                    libnvrm \
                    libnvrm_graphics \
                    libnvblit \
                    libnvddk_vic \
                    libnvrm_gpu \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    eks2_client \
                    tlk_daemon \
                    ss_status \
                    libtsec_wrapper_32 \
                    libtsec_wrapper \
                    libEGL_tegra_32 \
                    libtsec_wrapper_32 \
                    libnvglsi_32 \
                    libnvrmapi_tegra_32 \
                    libnvcpl_32 \
                    libphs_32 \
                    libGLESv1_CM_tegra_32 \
                    libglcore_32 \
                    libGLESv2_tegra_32 \
                    libnvwsi_32 \
                    libEGL_tegra \
                    libtsec_wrapper \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libnvcpl \
                    libphs \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvwsi \
                    libnvmm_audio_32 \
                    libnvmm_utils_32 \
                    libnvavp_32 \
                    libnvmm_32 \
                    libnvmm_msaudio_32 \
                    libnvmm_parser_32 \
                    libnvmm_contentpipe_32 \
                    libnvmm_writer_32 \
                    libnvmmlite_audio_32 \
                    libnvmmlite_utils_32 \
                    libnvmmlite_32 \
                    libnvmmlite_image_32 \
                    libnvparser_32 \
                    libnvtvmr_32 \
                    libnvddk_2d_v2_32 \
                    libnvmmlite_video_32 \
                    libnvtnr_32 \
                    libnvomx_32 \
                    libnvomxadaptor_32 \
                    libnvomxilclient_32 \
                    libwvm_32 \
                    libWVStreamControlAPI_L1_32 \
                    liboemcrypto_32 \
                    libdrmdecrypt_32 \
                    libdrmwvmplugin_32 \
                    libwvdrm_L1_32 \
                    libwvdrmengine_32 \
                    libcuda_32 \
                    libcuda \
                    pbc2 \
                    pbc.tegra \
                    pbc.tegra_32
