PRODUCT_PACKAGES += \
                    audio.primary.tegra \
                    libnvos \
                    libnvoice \
                    libnvaudiofx \
                    gralloc.tegra \
                    libnvgr \
                    libnvrm \
                    libnvrm_graphics \
                    libnvblit \
                    libnvddk_vic \
                    libnvrm_gpu \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    sensors.default.api_v1.3.mpl520.nvs \
                    libsensors.hal.nvs \
                    libsensors.hal-drivers.nvs \
                    libsensors.fusion.mpl520.nvs \
                    libsensors.prefusion.mpl520.nvs \
                    libmplmpu \
                    libmllite \
                    tlk_daemon \
                    ss_status \
                    libtsec_wrapper \
                    libEGL_tegra \
                    libtsec_wrapper \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libnvcpl \
                    libphs \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvwsi \
                    libnvmm_audio \
                    libnvmm_utils \
                    libnvavp \
                    libnvmm \
                    libnvmm_msaudio \
                    libnvmm_parser \
                    libnvmm_contentpipe \
                    libnvmm_writer \
                    libnvmmlite_audio \
                    libnvmmlite_utils \
                    libnvmmlite \
                    libnvmmlite_image \
                    libnvparser \
                    libnvtvmr \
                    libnvddk_2d_v2 \
                    libnvmmlite_video \
                    libnvtnr \
                    libcuda \
                    libnvomx \
                    libnvomxadaptor \
                    libnvomxilclient \
                    libwvm \
                    libWVStreamControlAPI_L1 \
                    liboemcrypto \
                    libdrmdecrypt \
                    libdrmwvmplugin \
                    libwvdrm_L1 \
                    libwvdrmengine
