PRODUCT_PACKAGES += \
                    audio.primary.tegra \
                    libnvos \
                    libnvoice \
                    libnvaudiofx \
                    gralloc.tegra \
                    libnvgr \
                    libnvrm \
                    libnvrm_graphics \
                    libnvblit \
                    libnvddk_vic \
                    libnvrm_gpu \
                    hdmi_cec.tegra \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    memtrack.tegra \
                    vulkan.tegra \
                    gatekeeper.tegra \
                    hdmi_cec.tegra \
                    gralloc.tegra \
                    libnvgr \
                    libnvos \
                    libnvrm \
                    libnvrm_graphics \
                    libnvblit \
                    libnvddk_vic \
                    libnvrm_gpu \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    tlk_daemon \
                    ss_status \
                    libEGL_tegra \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libphs \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libEGL_tegra \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libphs \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvomx \
                    libnvmm \
                    libnvmm_utils \
                    libnvavp \
                    libnvddk_2d_v2 \
                    libnvmm_contentpipe \
                    libnvmmlite \
                    libnvmmlite_utils \
                    libnvtvmr \
                    libnvomxadaptor \
                    libnvomxilclient \
                    rm_ts_server \
                    librm_ts_service \
                    ts.default \
                    librm31080 \
                    touch_para_10
