PRODUCT_PACKAGES += \
                    audio.primary.tegra_32 \
                    libnvos_32 \
                    libnvoice_32 \
                    libnvaudiofx_32 \
                    camera.tegra_32 \
                    libnvddk_2d_v2_32 \
                    libnvrm_32 \
                    libnvrm_graphics_32 \
                    libnvddk_vic_32 \
                    libnvgr_32 \
                    libnvmm_utils_32 \
                    libnvavp_32 \
                    libnvtvmr_32 \
                    libnvcam_imageencoder_32 \
                    libnvmm_32 \
                    libscf_32 \
                    libnvcamlog_32 \
                    libnvcamerautils_32 \
                    libcuda_32 \
                    libphs_32 \
                    libnvrm_gpu_32 \
                    libnvisp_v3_32 \
                    libnvmm_camera_v3_32 \
                    libnvodm_imager_32 \
                    libnvvicsi_v3_32 \
                    libopencv24_tegra_32 \
                    libtbb_32 \
                    libnvfnet_32 \
                    libnvfnetstorehdfx_32 \
                    libnvfnetstoredefog_32 \
                    libnvcamerahdr_v3_32 \
                    libnvcameranrr_32 \
                    libnvcudautils_32 \
                    gralloc.tegra_32 \
                    libnvblit_32 \
                    hdmi_cec.tegra_32 \
                    hwcomposer.tegra_32 \
                    libnvhwc_service_32 \
                    libtlk_secure_hdcp_up_32 \
                    libtsechdcp_32 \
                    keystore.tegra_32 \
                    memtrack.tegra_32 \
                    vulkan.tegra_32 \
                    hdmi_cec.tegra \
                    gralloc.tegra \
                    libnvgr \
                    libnvos \
                    libnvrm \
                    libnvrm_graphics \
                    libnvblit \
                    libnvddk_vic \
                    libnvrm_gpu \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    sensors.default.api_v1.4.mpl530.nvs \
                    libsensors.hal.nvs \
                    libsensors.hal-drivers.nvs \
                    libsensors.fusion.mpl530.nvs \
                    libsensors.prefusion.mpl530.nvs \
                    libmplmpu \
                    libmllite \
                    eks2_client \
                    tlk_daemon \
                    ss_status \
                    libtsec_wrapper_32 \
                    libtsec_wrapper \
                    libEGL_tegra_32 \
                    libtsec_wrapper_32 \
                    libnvglsi_32 \
                    libnvrmapi_tegra_32 \
                    libnvcpl_32 \
                    libGLESv1_CM_tegra_32 \
                    libglcore_32 \
                    libGLESv2_tegra_32 \
                    libnvwsi_32 \
                    libEGL_tegra \
                    libtsec_wrapper \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libnvcpl \
                    libphs \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvwsi \
                    glgps_nvidiaTegra2android \
                    gps.brcm \
                    libnvmm_audio_32 \
                    libnvmm_msaudio_32 \
                    libnvmm_parser_32 \
                    libnvmm_contentpipe_32 \
                    libnvmm_writer_32 \
                    libnvmmlite_audio_32 \
                    libnvmmlite_utils_32 \
                    libnvmmlite_32 \
                    libnvmmlite_image_32 \
                    libnvparser_32 \
                    libnvmmlite_video_32 \
                    libnvtnr_32 \
                    libnvomx_32 \
                    libnvomxadaptor_32 \
                    libnvomxilclient_32 \
                    rm_ts_server_32 \
                    librm_ts_service_32 \
                    ts.default_32 \
                    librm31080_32 \
                    touch_para_10_32 \
                    libwvm_32 \
                    libWVStreamControlAPI_L1_32 \
                    liboemcrypto_32 \
                    libdrmdecrypt_32 \
                    libdrmwvmplugin_32 \
                    libwvdrm_L1_32 \
                    libwvdrmengine_32 \
                    pbc2 \
                    pbc.tegra \
                    pbc.tegra_32
