PRODUCT_PACKAGES += \
                    audio.primary.tegra_32 \
                    libnvos_32 \
                    libnvoice_32 \
                    libnvaudiofx_32 \
                    gralloc.tegra_32 \
                    libnvgr_32 \
                    libnvrm_32 \
                    libnvrm_graphics_32 \
                    libnvblit_32 \
                    libnvddk_vic_32 \
                    libnvrm_gpu_32 \
                    hdmi_cec.tegra_32 \
                    hwcomposer.tegra_32 \
                    libnvhwc_service_32 \
                    libtlk_secure_hdcp_up_32 \
                    libtsechdcp_32 \
                    memtrack.tegra_32 \
                    vulkan.tegra_32 \
                    gatekeeper.tegra \
                    hdmi_cec.tegra \
                    gralloc.tegra \
                    libnvgr \
                    libnvos \
                    libnvrm \
                    libnvrm_graphics \
                    libnvblit \
                    libnvddk_vic \
                    libnvrm_gpu \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    tlk_daemon \
                    ss_status \
                    libtsec_wrapper_32 \
                    libtsec_wrapper \
                    libEGL_tegra_32 \
                    libnvglsi_32 \
                    libnvrmapi_tegra_32 \
                    libphs_32 \
                    libGLESv1_CM_tegra_32 \
                    libglcore_32 \
                    libGLESv2_tegra_32 \
                    libEGL_tegra \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libphs \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvomx_32 \
                    libnvmm_32 \
                    libnvmm_utils_32 \
                    libnvavp_32 \
                    libnvddk_2d_v2_32 \
                    libnvmm_contentpipe_32 \
                    libnvmmlite_32 \
                    libnvmmlite_utils_32 \
                    libnvtvmr_32 \
                    libnvomxadaptor_32 \
                    libnvomxilclient_32 \
                    rm_ts_server_32 \
                    librm_ts_service_32 \
                    ts.default_32 \
                    librm31080_32 \
                    touch_para_10_32
