PRODUCT_PACKAGES += \
                    audio.primary.tegra \
                    libnvoice \
                    libnvaudiofx \
                    tf_daemon \
                    libtsec_wrapper \
                    rm_ts_server \
                    librm_ts_service \
                    ts.default \
                    librm31080 \
                    glgps_nvidiaTegra2android \
                    gps.brcm \
                    libnvmm_audio \
                    libnvmm_utils \
                    libnvavp \
                    libnvmm \
                    libnvmm_msaudio \
                    libnvmm_parser \
                    libnvmm_contentpipe \
                    libnvmm_writer \
                    libnvmmlite_audio \
                    libnvmmlite_utils \
                    libnvmmlite \
                    libnvmmlite_image \
                    libnvparser \
                    libnvtvmr \
                    libardrv_dynamic \
                    libnvddk_2d_v2 \
                    libnvcms \
                    libnvmmlite_video \
                    libnvddk_2d \
                    libnvfusebypass \
                    libnvomx \
                    libnvodm_imager \
                    libnvodm_query \
                    libnvomxadaptor \
                    libnvomxilclient
