PRODUCT_PACKAGES += \
                    audio.primary.tegra \
                    libnvos \
                    libnvoice \
                    libnvaudiofx \
                    camera.tegra \
                    libnvddk_2d_v2 \
                    libnvrm \
                    libnvrm_graphics \
                    libnvddk_vic \
                    libnvgr \
                    libnvmm_utils \
                    libnvavp \
                    libnvtvmr \
                    libnvcam_imageencoder \
                    libnvmm \
                    libscf \
                    libnvcamlog \
                    libnvcamerautils \
                    libcuda \
                    libphs \
                    libnvrm_gpu \
                    libnvisp_v3 \
                    libnvmm_camera_v3 \
                    libnvodm_imager \
                    libnvvicsi_v3 \
                    libopencv24_tegra \
                    libtbb \
                    libnvfnet \
                    libnvfnetstorehdfx \
                    libnvfnetstoredefog \
                    libnvcamerahdr_v3 \
                    libnvcameranrr \
                    libnvcudautils \
                    gralloc.tegra \
                    libnvblit \
                    hwcomposer.tegra \
                    libnvhwc_service \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    keystore.tegra \
                    memtrack.tegra \
                    vulkan.tegra \
                    sensors.default.api_v1.3.mpl520.nvs \
                    libsensors.hal.nvs \
                    libsensors.hal-drivers.nvs \
                    libsensors.fusion.mpl520.nvs \
                    libsensors.prefusion.mpl520.nvs \
                    libmplmpu \
                    libmllite \
                    libril-icera \
                    icera-switcherd \
                    downloader \
                    tlk_daemon \
                    ss_status \
                    libtsec_wrapper \
                    rm_ts_server \
                    librm_ts_service \
                    ts.default \
                    librm31080 \
                    touch_para_10 \
                    libEGL_tegra \
                    libtsec_wrapper \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libnvcpl \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libGLESv2_tegra \
                    libnvwsi \
                    glgps_nvidiaTegra2android \
                    gps.brcm \
                    libnvmm_audio \
                    libnvmm_msaudio \
                    libnvmm_parser \
                    libnvmm_contentpipe \
                    libnvmm_writer \
                    libnvmmlite_audio \
                    libnvmmlite_utils \
                    libnvmmlite \
                    libnvmmlite_image \
                    libnvparser \
                    libnvmmlite_video \
                    libnvtnr \
                    libnvomx \
                    libnvomxadaptor \
                    libnvomxilclient \
                    libwvm \
                    libWVStreamControlAPI_L1 \
                    liboemcrypto \
                    libdrmdecrypt \
                    libdrmwvmplugin \
                    libwvdrm_L1 \
                    libwvdrmengine
