# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nvidia/foster/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nvidia/foster/proprietary/bin/bt_loader.sh:system/bin/bt_loader.sh \
    vendor/nvidia/foster/proprietary/bin/set_hwui_params.sh:system/bin/set_hwui_params.sh \
    vendor/nvidia/foster/proprietary/bin/ussr_setup.sh:system/bin/ussr_setup.sh \
    vendor/nvidia/foster/proprietary/bin/wifi_loader.sh:system/bin/wifi_loader.sh \
    vendor/nvidia/foster/proprietary/etc/enctune.conf:system/etc/enctune.conf \
    vendor/nvidia/foster/proprietary/etc/firmware/bcm43241.hcd:system/etc/firmware/bcm43241.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/BCM43341A0_001.001.030.0015.0000.hcd:system/etc/firmware/BCM43341A0_001.001.030.0015.0000.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/BCM43341B0_002.001.014.0008.0011.hcd:system/etc/firmware/BCM43341B0_002.001.014.0008.0011.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/bcm4335.hcd:system/etc/firmware/bcm4335.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/bcm4350.hcd:system/etc/firmware/bcm4350.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/acr_ucode.bin:system/etc/firmware/gm20b/acr_ucode.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/fecs.bin:system/etc/firmware/gm20b/fecs.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/fecs_sig.bin:system/etc/firmware/gm20b/fecs_sig.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpccs.bin:system/etc/firmware/gm20b/gpccs.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpmu_ucode_desc.bin:system/etc/firmware/gm20b/gpmu_ucode_desc.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpmu_ucode_image.bin:system/etc/firmware/gm20b/gpmu_ucode_image.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpu2cde.bin:system/etc/firmware/gm20b/gpu2cde.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/NETB_img.bin:system/etc/firmware/gm20b/NETB_img.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/pmu_bl.bin:system/etc/firmware/gm20b/pmu_bl.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/pmu_sig.bin:system/etc/firmware/gm20b/pmu_sig.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec020.fw:system/etc/firmware/tegra21x/nvhost_nvdec020.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec020_ns.fw:system/etc/firmware/tegra21x/nvhost_nvdec020_ns.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec020_prod.fw:system/etc/firmware/tegra21x/nvhost_nvdec020_prod.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec_bl020.fw:system/etc/firmware/tegra21x/nvhost_nvdec_bl020.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec_bl020_prod.fw:system/etc/firmware/tegra21x/nvhost_nvdec_bl020_prod.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec_bl_no_wpr020.fw:system/etc/firmware/tegra21x/nvhost_nvdec_bl_no_wpr020.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvenc050.fw:system/etc/firmware/tegra21x/nvhost_nvenc050.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvjpg010.fw:system/etc/firmware/tegra21x/nvhost_nvjpg010.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_tsec.fw:system/etc/firmware/tegra21x/nvhost_tsec.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/vic04_ucode.bin:system/etc/firmware/tegra21x/vic04_ucode.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x_xusb_firmware:system/etc/firmware/tegra21x_xusb_firmware \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra_xusb_firmware:system/etc/firmware/tegra_xusb_firmware \
    vendor/nvidia/foster/proprietary/etc/hdcpsrm/hdcp1x.srm:system/etc/hdcpsrm/hdcp1x.srm \
    vendor/nvidia/foster/proprietary/etc/hdcpsrm/hdcp2x.srm:system/etc/hdcpsrm/hdcp2x.srm \
    vendor/nvidia/foster/proprietary/etc/hdcpsrm/hdcp2xtest.srm:system/etc/hdcpsrm/hdcp2xtest.srm \
    vendor/nvidia/foster/proprietary/etc/nvram_4354.txt:system/etc/nvram_4354.txt \
    vendor/nvidia/foster/proprietary/etc/nvram_foster_e_4354.txt:system/etc/nvram_foster_e_4354.txt \
    vendor/nvidia/foster/proprietary/etc/nvram_foster_e_antenna_tuned_4354.txt:system/etc/nvram_foster_e_antenna_tuned_4354.txt \
    vendor/nvidia/foster/proprietary/etc/ussrd.conf:system/etc/ussrd.conf \
    vendor/nvidia/foster/proprietary/lib/libopencv24_tegra.so:system/lib/libopencv24_tegra.so \
    vendor/nvidia/foster/proprietary/lib/libtbb.so:system/lib/libtbb.so
