# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nvidia/foster/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nvidia/foster/proprietary/bin/set_hwui_params.sh:system/bin/set_hwui_params.sh \
    vendor/nvidia/foster/proprietary/bin/ussr_setup.sh:system/bin/ussr_setup.sh \
    vendor/nvidia/foster/proprietary/bin/wifi_loader.sh:system/bin/wifi_loader.sh \
    vendor/nvidia/foster/proprietary/etc/enctune.conf:system/etc/enctune.conf \
    vendor/nvidia/foster/proprietary/etc/firmware/bcm43241.hcd:system/etc/firmware/bcm43241.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/BCM43341A0_001.001.030.0015.0000.hcd:system/etc/firmware/BCM43341A0_001.001.030.0015.0000.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/BCM43341B0_002.001.014.0008.0011.hcd:system/etc/firmware/BCM43341B0_002.001.014.0008.0011.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/bcm4335.hcd:system/etc/firmware/bcm4335.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/bcm4350.hcd:system/etc/firmware/bcm4350.hcd \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/acr_ucode.bin:system/etc/firmware/gm20b/acr_ucode.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/fecs.bin:system/etc/firmware/gm20b/fecs.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/fecs_sig.bin:system/etc/firmware/gm20b/fecs_sig.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpccs.bin:system/etc/firmware/gm20b/gpccs.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpmu_ucode_desc.bin:system/etc/firmware/gm20b/gpmu_ucode_desc.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpmu_ucode_image.bin:system/etc/firmware/gm20b/gpmu_ucode_image.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/gpu2cde.bin:system/etc/firmware/gm20b/gpu2cde.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/NETB_img.bin:system/etc/firmware/gm20b/NETB_img.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/pmu_bl.bin:system/etc/firmware/gm20b/pmu_bl.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/gm20b/pmu_sig.bin:system/etc/firmware/gm20b/pmu_sig.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec020.fw:system/etc/firmware/tegra21x/nvhost_nvdec020.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec020_ns.fw:system/etc/firmware/tegra21x/nvhost_nvdec020_ns.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec020_prod.fw:system/etc/firmware/tegra21x/nvhost_nvdec020_prod.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec_bl020.fw:system/etc/firmware/tegra21x/nvhost_nvdec_bl020.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec_bl020_prod.fw:system/etc/firmware/tegra21x/nvhost_nvdec_bl020_prod.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvdec_bl_no_wpr020.fw:system/etc/firmware/tegra21x/nvhost_nvdec_bl_no_wpr020.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvenc050.fw:system/etc/firmware/tegra21x/nvhost_nvenc050.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_nvjpg010.fw:system/etc/firmware/tegra21x/nvhost_nvjpg010.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/nvhost_tsec.fw:system/etc/firmware/tegra21x/nvhost_tsec.fw \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x/vic04_ucode.bin:system/etc/firmware/tegra21x/vic04_ucode.bin \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra_xusb_firmware:system/etc/firmware/tegra_xusb_firmware \
    vendor/nvidia/foster/proprietary/etc/firmware/tegra21x_xusb_firmware:system/etc/firmware/tegra21x_xusb_firmware \
    vendor/nvidia/foster/proprietary/etc/hdcpsrm/hdcp1x.srm:system/etc/hdcpsrm/hdcp1x.srm \
    vendor/nvidia/foster/proprietary/etc/hdcpsrm/hdcp2x.srm:system/etc/hdcpsrm/hdcp2x.srm \
    vendor/nvidia/foster/proprietary/etc/hdcpsrm/hdcp2xtest.srm:system/etc/hdcpsrm/hdcp2xtest.srm \
    vendor/nvidia/foster/proprietary/etc/nvram_43241.txt:system/etc/nvram_43241.txt \
    vendor/nvidia/foster/proprietary/etc/ussrd.conf:system/etc/ussrd.conf \
    vendor/nvidia/foster/proprietary/lib/hw/power.tegra.so:system/lib/hw/power.tegra.so \
    vendor/nvidia/foster/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/nvidia/foster/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/nvidia/foster/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/nvidia/foster/proprietary/lib/libopencv24_tegra.so:system/lib/libopencv24_tegra.so \
    vendor/nvidia/foster/proprietary/lib/libtbb.so:system/lib/libtbb.so \
    vendor/nvidia/foster/proprietary/vendor/bin/btmacwriter:system/vendor/bin/btmacwriter \
    vendor/nvidia/foster/proprietary/vendor/bin/tegrastats:system/vendor/bin/tegrastats \
    vendor/nvidia/foster/proprietary/vendor/firmware/bcm43241/fw_bcmdhd.bin:system/vendor/firmware/bcm43241/fw_bcmdhd.bin \
    vendor/nvidia/foster/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/egl/libEGL_tegra.so:system/vendor/lib64/egl/libEGL_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/egl/libEGL_tegra.so:system/vendor/lib/egl/libEGL_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/egl/libGLESv1_CM_tegra.so:system/vendor/lib64/egl/libGLESv1_CM_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:system/vendor/lib/egl/libGLESv1_CM_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/egl/libGLESv2_tegra.so:system/vendor/lib64/egl/libGLESv2_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/egl/libGLESv2_tegra.so:system/vendor/lib/egl/libGLESv2_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/hw/audio.primary.tegra.so:system/vendor/lib/hw/audio.primary.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/hw/gralloc.tegra.so:system/vendor/lib/hw/gralloc.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/hw/gralloc.tegra.so:system/vendor/lib64/hw/gralloc.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/hw/hwcomposer.tegra.so:system/vendor/lib/hw/hwcomposer.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/hw/hwcomposer.tegra.so:system/vendor/lib64/hw/hwcomposer.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/hw/memtrack.tegra.so:system/vendor/lib/hw/memtrack.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/hw/memtrack.tegra.so:system/vendor/lib64/hw/memtrack.tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libaudioavp.so:system/vendor/lib/libaudioavp.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libcuda.so:system/vendor/lib/libcuda.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libglcore.so:system/vendor/lib/libglcore.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libglcore.so:system/vendor/lib64/libglcore.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvaudiofx.so:system/vendor/lib/libnvaudiofx.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvaudioservice.so:system/vendor/lib/libnvaudioservice.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvblit.so:system/vendor/lib/libnvblit.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvcapaudioservice.so:system/vendor/lib/libnvcapaudioservice.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvcapclk.so:system/vendor/lib/libnvcapclk.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvcms.so:system/vendor/lib/libnvcms.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvcpl.so:system/vendor/lib/libnvcpl.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvcpl.so:system/vendor/lib64/libnvcpl.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvddk_2d_v2.so:system/vendor/lib/libnvddk_2d_v2.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvddk_vic.so:system/vendor/lib/libnvddk_vic.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvfusebypass.so:system/vendor/lib/libnvfusebypass.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvglsi.so:system/vendor/lib/libnvglsi.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvglsi.so:system/vendor/lib64/libnvglsi.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvgr.so:system/vendor/lib/libnvgr.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvgr.so:system/vendor/lib64/libnvgr.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvhwc_service.so:system/vendor/lib/libnvhwc_service.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmm_audio.so:system/vendor/lib/libnvmm_audio.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmm_contentpipe.so:system/vendor/lib/libnvmm_contentpipe.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmmlite_audio.so:system/vendor/lib/libnvmmlite_audio.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmmlite_image.so:system/vendor/lib/libnvmmlite_image.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmmlite.so:system/vendor/lib/libnvmmlite.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmmlite_utils.so:system/vendor/lib/libnvmmlite_utils.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmmlite_video.so:system/vendor/lib/libnvmmlite_video.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmm_parser.so:system/vendor/lib/libnvmm_parser.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmm.so:system/vendor/lib/libnvmm.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmm_utils.so:system/vendor/lib/libnvmm_utils.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvmm_writer.so:system/vendor/lib/libnvmm_writer.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvodm_imager.so:system/vendor/lib/libnvodm_imager.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvoice.so:system/vendor/lib/libnvoice.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvomxadaptor.so:system/vendor/lib/libnvomxadaptor.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvomxilclient.so:system/vendor/lib/libnvomxilclient.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvomx.so:system/vendor/lib/libnvomx.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvos.so:system/vendor/lib/libnvos.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvos.so:system/vendor/lib64/libnvos.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvparser.so:system/vendor/lib/libnvparser.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvrmapi_tegra.so:system/vendor/lib/libnvrmapi_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvrmapi_tegra.so:system/vendor/lib64/libnvrmapi_tegra.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvrm_graphics.so:system/vendor/lib/libnvrm_graphics.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvrm_graphics.so:system/vendor/lib64/libnvrm_graphics.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvrm.so:system/vendor/lib/libnvrm.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvrm.so:system/vendor/lib64/libnvrm.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvstitching.so:system/vendor/lib/libnvstitching.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvtnr.so:system/vendor/lib/libnvtnr.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvtvmr.so:system/vendor/lib/libnvtvmr.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvwinsys.so:system/vendor/lib/libnvwinsys.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libnvwsi.so:system/vendor/lib/libnvwsi.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libnvwsi.so:system/vendor/lib64/libnvwsi.so \
    vendor/nvidia/foster/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libphs.so:system/vendor/lib/libphs.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libphs.so:system/vendor/lib64/libphs.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libtlk_secure_hdcp_up.so:system/vendor/lib/libtlk_secure_hdcp_up.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libtsechdcp.so:system/vendor/lib/libtsechdcp.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libtsechdcp.so:system/vendor/lib64/libtsechdcp.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libtsec_wrapper.so:system/vendor/lib/libtsec_wrapper.so \
    vendor/nvidia/foster/proprietary/vendor/lib64/libtsec_wrapper.so:system/vendor/lib64/libtsec_wrapper.so \
    vendor/nvidia/foster/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so
