# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nvidia/wx_na_do/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nvidia/wx_na_do/proprietary/etc/ril_atc.config:system/etc/ril_atc.config \
    vendor/nvidia/wx_na_do/proprietary/vendor/bin/crash-check-arm:system/vendor/bin/crash-check-arm \
    vendor/nvidia/wx_na_do/proprietary/vendor/bin/downloader:system/vendor/bin/downloader \
    vendor/nvidia/wx_na_do/proprietary/vendor/bin/icera-crashlogs:system/vendor/bin/icera-crashlogs \
    vendor/nvidia/wx_na_do/proprietary/vendor/bin/icera-loader:system/vendor/bin/icera-loader \
    vendor/nvidia/wx_na_do/proprietary/vendor/bin/icera_log_serial_arm:system/vendor/bin/icera_log_serial_arm \
    vendor/nvidia/wx_na_do/proprietary/vendor/bin/icera-switcherd:system/vendor/bin/icera-switcherd \
    vendor/nvidia/wx_na_do/proprietary/vendor/lib/libril-icera.so:system/vendor/lib/libril-icera.so \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729/audioConfig.bin:system/vendor/firmware/icera/nvidia-e1729/audioConfig.bin \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729/loader.wrapped:system/vendor/firmware/icera/nvidia-e1729/loader.wrapped \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729/modem.wrapped:system/vendor/firmware/icera/nvidia-e1729/modem.wrapped \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729/productConfig.bin:system/vendor/firmware/icera/nvidia-e1729/productConfig.bin \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729/secondary_boot.wrapped:system/vendor/firmware/icera/nvidia-e1729/secondary_boot.wrapped \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729-nala/audioConfig.bin:system/vendor/firmware/icera/nvidia-e1729-nala/audioConfig.bin \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729-nala/loader.wrapped:system/vendor/firmware/icera/nvidia-e1729-nala/loader.wrapped \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729-nala/modem.wrapped:system/vendor/firmware/icera/nvidia-e1729-nala/modem.wrapped \
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729-nala/productConfig.bin:system/vendor/firmware/icera/nvidia-e1729-nala/productConfig.bin
    vendor/nvidia/wx_na_do/proprietary/vendor/firmware/icera/nvidia-e1729-nala/secondary_boot.wrapped:system/vendor/firmware/icera/nvidia-e1729-nala/secondary_boot.wrapped
